apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::631231558475:role/EC2-full
      username: eks-node
      groups:
        - system:masters
    - rolearn: arn:aws:iam::631231558475:role/HR-dev-eks-nodegroup-role
      username: eks-node
      groups:
        - system:masters    
  mapUsers: |
    - userarn: arn:aws:iam::631231558475:user/
      username: your-user
      groups:
        - system:masters
