apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3 # Number of NGINX pods to run
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest  # Use the official NGINX image
          ports:
            - containerPort: 80  # Expose port 80 on the NGINX container
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80  # Port on the service
      targetPort: 80  # Port on the container
  type: LoadBalancer  # Use LoadBalancer to expose the service externally (if you're on a cloud provider like AWS, GCP, etc.)

